import { Button,Slider, Switch } from "std-widgets.slint";
export component Ctrl inherits Rectangle {

    in-out property <[string]> songs: [];
    in-out property <bool> loop;
    in-out property <int> nowtime;
    in-out property <int> maxtime;
    
    callback play();
    callback pause();
    callback stop();
    callback previous();
    callback next();
    callback open_folder();
    callback toggle_loop(bool);
    
    HorizontalLayout {
        alignment: space-between;
        Button { text: "Play"; clicked => {play()} }
        Button { text: "Pause"; clicked => {pause()} }
        Button { text: "Stop"; clicked => {stop() }}
        Button { text: "Previous"; clicked => {previous()} }
        Button { text: "Next"; clicked => {next() }}
        Button { text: "LoadFile"; clicked => {open_folder() }}
        xh := Switch {
            text: "循环播放";
            checked: root.loop;
            toggled => {
                toggle_loop(root.loop)
            }
        }
    }
}