
import { StandardTableView } from "std-widgets.slint";
export component List inherits Rectangle {
    in-out property <[[StandardListViewItem]]> list;
    callback select(int);
    StandardTableView { 
        width: parent.width;
        height: parent.height;
        current-row-changed(i) => {select(i)}
        columns: [
            {title:"SongName"},
            {title:"Artist"},
            {title:"Album"},
            {title:"Year"},
            // {title:"Genre"},
        ];
        rows: root.list;
     }
}