import { ListView, Button, Switch, Slider } from "std-widgets.slint";
import { List } from "page/list.slint";
import { Ctrl } from "page/ctrl.slint";
export component App inherits Window {
    width: 1280px;
    height: 720px;
    title: "Music Player";

    in-out property list <=> list.list;
    in-out property loop <=> ctrl.loop;
    in-out property nowtime <=> ctrl.nowtime;
    in-out property maxtime <=> ctrl.maxtime;
    callback play <=> ctrl.play;
    callback pause <=> ctrl.pause;
    callback stop <=> ctrl.stop;
    callback previous <=> ctrl.previous;
    callback next <=> ctrl.next;
    callback open_folder <=> ctrl.open_folder;
    callback toggle_loop <=> ctrl.toggle_loop;
    callback select <=> list.select;

    VerticalLayout {
        alignment: space-between;
        spacing: 10px;
        padding: 10px;
        height: parent.height;
        HorizontalLayout {
            height: root.height * 0.85;
            list := List {
                height: parent.height;
            }
        }
        VerticalLayout {
            height: root.height * 0.08;
            HorizontalLayout {
                Slider {
                    width: 800px;
                    value: nowtime;
                    minimum: 0;
                    maximum: maxtime;
                }
                Rectangle {
                    Text {
                        text: @tr("{} - {}",nowtime,maxtime);
                    }
                }
            }
            ctrl := Ctrl {
    
            }
        }
        
        
    }

    
}
